### ISSUE TITLE
Make a small widget size of 1x1

### ISSUE THREAD

**Issue by OmlineEditor** [impalex/knockonports#13]
now it is possible to make widgets of 2x1 size and it is possible to switch buttons inside the widget where you need to make a knock port.

Make a small widget size of 1x1 and without buttons only one selected server.
Save space on small screens.

**Comment by impalex** [comment]
Use shortcuts.
![image](https://user-images.githubusercontent.com/13515747/91576946-7b6c0e00-e961-11ea-8ab7-224752eaa153.png)

**Comment by infabo** [comment]
~I am very sad. The shortcut feature was removed from version 2.0. Now there is only a very huge widget left.~

Oh, it is still available. I just had to re-create the shortcut. The existing shortcut was broken after upgrade to v2.

**Comment by impalex** [comment]
No one removed the shortcuts. As before, shortcuts are available on Android 8 and above. Shortcuts cannot be created for sequences without a name.
That the old shortcuts “broke” is expected behavior. Alas, too much has changed in the application and it was not possible to save them.
![Image](https://github.com/user-attachments/assets/458357bc-20ed-4133-b531-16207bcf1a87)
![Image](https://github.com/user-attachments/assets/3ebf475a-eafb-47cc-bcd6-3aa75a8030af)
![Image](https://github.com/user-attachments/assets/1f19ff23-e984-4415-9728-1f604e5978dd)
